defaults:
  - default
  - override cluster: rsc
  - override dataset: flores200.ablation.v4.2
  - override model_type: moe

train_prefix: moe
validate_interval_updates: 10000
save_interval_updates: 5000
best_checkpoint_metric: "ppl"
encoder_langtok: src
ddp_backend: fully_sharded
lr: 0.004
warmup: 8000
max_tokens: 4096
update_freq: 4
num_nodes: 8
num_gpus_per_node: 8
temp: 1
dropout: 0
max_time_mins: 8000
